[package]
name = "day_24"
version = "0.1.0"
authors = ["Brian Beach <coder@beachfamily.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conway_life = { path = "../conway_life" }
lazy_static = "1"
regex = "1"
